-- migrate:up
-- Staff and the audit log (founder decision, 2026-10-10: Buildium/AppFolio parity, "do 1
-- through 3").
--
-- Every write to a trust record or the ledger is recorded in trust_audit_log: when (the
-- database's clock, UTC), what (the table, insert/update/delete, the row as written and, for an
-- update, the row before), who (the staff member the application named, if it named one) and
-- through which database role. Nothing in Phase 0 logs anyone in, so the application names the
-- person: it sets `trust.staff_id` to one of the PMC's staff (trust_staff) for the session or
-- the transaction (set_config('trust.staff_id', <id>, true)). A staff member of another PMC, or
-- an id that is no staff member, is refused with the write. A write with no staff named is
-- recorded too, as not recorded; requiring one waits for logins (out of scope for Phase 0).
--
-- The log is append-only, like the ledger, and only the trigger writes it: the app and the AI
-- read it. Each audited table gets the trust_audit trigger; tests/test_audit_log.py fails on a
-- trust table that has none, so a new table can't be left out. Not audited: the log itself,
-- trust_idempotency_keys (written only with the transfers it records, which are audited),
-- pgledger_accounts and pgledger_entries (every transfer updates two balances and writes two
-- entries; the transfer row says it all).
--
-- trust_report_audit_log lists a PMC's log over a period of whole days (UTC).

-- On a live database, give up rather than queue behind a long transaction while holding locks.
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

CREATE TABLE trust_staff (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    pmc_id uuid NOT NULL REFERENCES trust_pmcs (pmc_id),
    display_name text NOT NULL CHECK (display_name <> ''),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (pmc_id, id)
);

REVOKE ALL ON trust_staff FROM PUBLIC;
-- Like the other records: the app adds and renames staff, never deletes them.
GRANT SELECT, INSERT ON trust_staff TO trust_app;
GRANT UPDATE (display_name) ON trust_staff TO trust_app;
GRANT SELECT ON trust_staff TO trust_ai_agent;

CREATE TABLE trust_audit_log (
    -- Only the trigger inserts, and it never names an id.
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pmc_id uuid NOT NULL REFERENCES trust_pmcs (pmc_id),
    at timestamptz NOT NULL DEFAULT clock_timestamp(),
    staff_id uuid,
    db_role text NOT NULL,
    action text NOT NULL CHECK (action IN ('insert', 'update', 'delete')),
    table_name text NOT NULL,
    row_data jsonb NOT NULL,
    before jsonb,
    CHECK ((action = 'update') = (before IS NOT NULL)),
    FOREIGN KEY (pmc_id, staff_id) REFERENCES trust_staff (pmc_id, id)
);

CREATE INDEX trust_audit_log_pmc_id_at ON trust_audit_log (pmc_id, at);

CREATE TRIGGER trust_append_only
BEFORE UPDATE OR DELETE OR TRUNCATE ON trust_audit_log
FOR EACH STATEMENT EXECUTE FUNCTION trust_refuse_ledger_rewrite();

REVOKE ALL ON trust_audit_log FROM PUBLIC;
GRANT SELECT ON trust_audit_log TO trust_app, trust_ai_agent;

-- Record one write. Runs as the owner: nobody else may write the log.
CREATE FUNCTION trust_audit() RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
-- A row's times are written into the log in UTC, whatever the writer's session time zone.
SET timezone = 'UTC'
AS $$
DECLARE
    v_row jsonb := to_jsonb(CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END);
    v_pmc uuid;
    v_staff uuid := nullif(current_setting('trust.staff_id', true), '')::uuid;
BEGIN
    IF TG_TABLE_NAME = 'pgledger_transfers' THEN
        SELECT t.pmc_id INTO v_pmc
        FROM trust_ledger_accounts AS t WHERE t.ledger_account_id = v_row ->> 'from_account_id';
    ELSE
        v_pmc := (v_row ->> 'pmc_id')::uuid;
    END IF;

    IF v_staff IS NOT NULL AND NOT EXISTS (
        SELECT s.id FROM trust_staff AS s WHERE s.id = v_staff AND s.pmc_id = v_pmc
    ) THEN
        RAISE EXCEPTION 'trust: % is not a staff member of PMC %', v_staff, v_pmc
            USING ERRCODE = 'invalid_parameter_value',
                  HINT = 'Set trust.staff_id to one of the PMC''s staff (trust_staff), or not at all.';
    END IF;

    INSERT INTO trust_audit_log (pmc_id, staff_id, db_role, action, table_name, row_data, before)
    VALUES (
        v_pmc, v_staff,
        -- The role the session acts as: SET ROLE's, else the one it logged in with. (The
        -- owner's, inside a write path that runs as the owner, is never the one recorded.)
        coalesce(nullif(current_setting('role'), 'none'), session_user),
        lower(TG_OP), TG_TABLE_NAME, v_row,
        CASE WHEN TG_OP = 'UPDATE' THEN to_jsonb(OLD) END
    );
    RETURN NULL;
END;
$$;

REVOKE ALL ON FUNCTION trust_audit() FROM PUBLIC;

DO $$
DECLARE
    v_table text;
BEGIN
    FOREACH v_table IN ARRAY ARRAY[
        'pgledger_transfers',
        'trust_pmcs', 'trust_bank_accounts', 'trust_owners', 'trust_properties', 'trust_tenants',
        'trust_vendors', 'trust_staff', 'trust_ledger_accounts', 'trust_reconciliations',
        'trust_units', 'trust_leases', 'trust_lease_tenants', 'trust_charges',
        'trust_charge_payments', 'trust_payment_reversals', 'trust_management_agreements',
        'trust_management_fees', 'trust_leasing_fees', 'trust_owner_draws', 'trust_bills',
        'trust_bill_approvals', 'trust_bill_payments', 'trust_work_orders',
        'trust_work_order_steps', 'trust_late_fee_policies', 'trust_late_fees',
        'trust_opening_balances'
    ] LOOP
        EXECUTE format(
            'CREATE TRIGGER trust_audit AFTER INSERT OR UPDATE OR DELETE ON %I '
            'FOR EACH ROW EXECUTE FUNCTION trust_audit()', v_table
        );
    END LOOP;
END;
$$;

CREATE FUNCTION trust_report_audit_log(
    p_pmc_id uuid,
    p_from date,
    p_to date
) RETURNS TABLE (
    line integer,
    item text,
    at text,
    staff text,
    db_role text,
    action text,
    record text,
    detail text
)
LANGUAGE plpgsql
STABLE
SET search_path = public, pg_temp
AS $$
#variable_conflict use_column
DECLARE
    v_start timestamptz := p_from::timestamp AT TIME ZONE 'UTC';
    v_end timestamptz := (p_to + 1)::timestamp AT TIME ZONE 'UTC';
BEGIN
    IF p_from IS NULL OR p_to IS NULL OR p_to < p_from THEN
        RAISE EXCEPTION 'trust: an audit log runs from a day to the same day or a later one '
            '(got % to %)', p_from, p_to
            USING ERRCODE = 'invalid_parameter_value';
    END IF;
    IF NOT EXISTS (SELECT pmc.pmc_id FROM trust_pmcs AS pmc WHERE pmc.pmc_id = p_pmc_id) THEN
        RAISE EXCEPTION 'trust: no PMC %', p_pmc_id
            USING ERRCODE = 'invalid_parameter_value';
    END IF;

    RETURN QUERY
    WITH holders AS (
        SELECT t.ledger_account_id AS id,
               t.kind || ': ' || CASE t.kind
                   WHEN 'bank_cash' THEN b.display_name
                   WHEN 'owner_property' THEN o.display_name || ' / ' || pr.display_name
                   WHEN 'vendor_payable' THEN v.display_name
                   WHEN 'pmc_income' THEN pmc.display_name
                   ELSE tn.display_name
               END AS holder
        FROM trust_ledger_accounts AS t
        JOIN trust_bank_accounts AS b ON b.id = t.bank_account_id
        JOIN trust_pmcs AS pmc ON pmc.pmc_id = t.pmc_id
        LEFT JOIN trust_owners AS o ON o.id = t.owner_id
        LEFT JOIN trust_properties AS pr ON pr.id = t.property_id
        LEFT JOIN trust_tenants AS tn ON tn.id = t.tenant_id
        LEFT JOIN trust_vendors AS v ON v.id = t.vendor_id
        WHERE t.pmc_id = p_pmc_id
    ),
    changes AS (
        SELECT a.id, a.at, coalesce(s.display_name, 'not recorded') AS staff, a.db_role,
               a.action, regexp_replace(a.table_name, '^(trust|pgledger)_', '') AS record,
               CASE
                   -- A transfer: how much, from and to whom, dated when, and its memo.
                   WHEN a.table_name = 'pgledger_transfers' THEN
                       (a.row_data ->> 'amount') || ' from ' || f.holder || ' to ' || t.holder
                       || ' dated ' || (a.row_data ->> 'event_at')
                       || coalesce(' - ' || (a.row_data -> 'metadata' ->> 'memo'), '')
                   -- An update: each field it changed, from what to what.
                   WHEN a.action = 'update' THEN (
                       SELECT coalesce(string_agg(
                           n.key || ': ' || coalesce(a.before ->> n.key, 'null') || ' to '
                           || coalesce(n.value #>> '{}', 'null'),
                           ', ' ORDER BY n.key COLLATE "C"
                       ), 'no change')
                       FROM jsonb_each(a.row_data) AS n
                       WHERE n.value IS DISTINCT FROM a.before -> n.key
                   )
                   -- Anything else: its fields, but ids and the clock's time of writing it
                   -- (the log's own time says when).
                   ELSE (
                       SELECT string_agg(
                           n.key || ': ' || n.value, ', ' ORDER BY n.key COLLATE "C"
                       )
                       FROM jsonb_each_text(a.row_data) AS n
                       WHERE n.value IS NOT NULL AND n.key <> 'id' AND n.key NOT LIKE '%\_id'
                         AND n.key NOT IN ('created_at', 'approved_at')
                   )
               END AS detail
        FROM trust_audit_log AS a
        LEFT JOIN trust_staff AS s ON s.id = a.staff_id
        LEFT JOIN holders AS f ON f.id = a.row_data ->> 'from_account_id'
        LEFT JOIN holders AS t ON t.id = a.row_data ->> 'to_account_id'
        WHERE a.pmc_id = p_pmc_id AND a.at >= v_start AND a.at < v_end
    ),
    lines AS (
        SELECT 0 AS section, NULL::bigint AS id, 'PMC' AS item, NULL::timestamptz AS at,
               pmc.display_name AS staff, NULL::text AS db_role, NULL::text AS action,
               NULL::text AS record, NULL::text AS detail
        FROM trust_pmcs AS pmc WHERE pmc.pmc_id = p_pmc_id
        UNION ALL
        SELECT 1, NULL, 'period', NULL,
               to_char(p_from, 'YYYY-MM-DD') || ' to ' || to_char(p_to, 'YYYY-MM-DD')
                   || ', whole days UTC',
               NULL, NULL, NULL, NULL
        UNION ALL
        SELECT 2, c.id, 'change', c.at, c.staff, c.db_role, c.action, c.record, c.detail
        FROM changes AS c
        UNION ALL
        SELECT 3, NULL, 'total', NULL, NULL, NULL, NULL, NULL,
               (SELECT count(*) FROM changes) || ' changes'
    )
    SELECT row_number() OVER (ORDER BY l.section, l.id)::integer,
           l.item,
           to_char(l.at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS.US'),
           -- The PMC's name and the period sit in the staff column of the first two lines.
           l.staff,
           l.db_role,
           l.action,
           l.record,
           l.detail
    FROM lines AS l
    ORDER BY 1;
END;
$$;

REVOKE ALL ON FUNCTION trust_report_audit_log(uuid, date, date) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION trust_report_audit_log(uuid, date, date) TO trust_app, trust_ai_agent;

-- migrate:down
DO $$
BEGIN
    RAISE EXCEPTION 'audit_log cannot be rolled back: the audit log is a record';
END;
$$;
